services:
  postgres:
    image: postgres:15-alpine
    container_name: monster-mart-project
    restart: always
    environment:
      POSTGRES_USER: rolez
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monstermart
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: